In [50]:
from google.colab import files
uploaded = files.upload()

In [71]:
import numpy as np
import pandas as pd
import warnings 
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import CategoricalNB
warnings.filterwarnings("ignore")

df = pd.read_csv('playtennis.csv')
df

outlook  temp humidity  windy play
0      sunny   hot     high  False   no
1      sunny   hot     high   True   no
2   overcast   hot     high  False  yes
3      rainy  mild     high  False  yes
4      rainy  cool   normal  False  yes
5      rainy  cool   normal   True   no
6   overcast  cool   normal   True  yes
7      sunny  mild     high  False   no
8      sunny  cool   normal  False  yes
9      rainy  mild   normal  False  yes
10     sunny  mild   normal   True  yes
11  overcast  mild     high   True  yes
12  overcast   hot   normal  False  yes
13     rainy  mild     high   True   no
14  overcast   hot     high  False  yes
15     rainy  mild     high  False  yes
16     sunny  mild     high  False   no
17     rainy  cool   normal   True   no
18     sunny   hot     high  False   no
19     sunny   hot     high   True   no

In [72]:
X = df.drop(['play'], axis=1)
y = df['play']

In [73]:
def LabelEncode(data, columns):
  for i in columns:
    lb = LabelEncoder().fit_transform(data[i])
    data[i+'_'] = lb

In [74]:
f_columns = ['outlook', 'temp', 'humidity', 'windy']
LabelEncode(X, f_columns)

In [75]:
y_le = LabelEncoder()
y1 = y_le.fit_transform(y)
y1

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0])

In [76]:
X1 = X[['outlook_', 'temp_', 'humidity_', 'windy_']]
X1

outlook_  temp_  humidity_  windy_
0          2      1          0       0
1          2      1          0       1
2          0      1          0       0
3          1      2          0       0
4          1      0          1       0
5          1      0          1       1
6          0      0          1       1
7          2      2          0       0
8          2      0          1       0
9          1      2          1       0
10         2      2          1       1
11         0      2          0       1
12         0      1          1       0
13         1      2          0       1
14         0      1          0       0
15         1      2          0       0
16         2      2          0       0
17         1      0          1       1
18         2      1          0       0
19         2      1          0       1

In [77]:
model = CategoricalNB()
model.fit(X1, y1)
print(model.feature_log_prob_)

[array([[-2.48490665, -1.09861229, -0.5389965 ],
       [-0.84729786, -1.02961942, -1.54044504]]), array([[-1.38629436, -0.87546874, -1.09861229],
       [-1.25276297, -1.25276297, -0.84729786]]), array([[-0.31845373, -1.29928298],
       [-0.77318989, -0.61903921]]), array([[-0.78845736, -0.6061358 ],
       [-0.36772478, -1.178655  ]])]


In [78]:
print(model.category_count_)

[array([[0., 3., 6.],
       [5., 4., 2.]]), array([[2., 4., 3.],
       [3., 3., 5.]]), array([[7., 2.],
       [5., 6.]]), array([[4., 5.],
       [8., 3.]])]


In [83]:
new_input = [[2, 0, 1, 1], [1, 2, 1, 0]]
y_prob_pred = model.predict_proba(new_input)
y_prob_pred

array([[0.6363419 , 0.3636581 ],
       [0.16493552, 0.83506448]])

In [82]:
y_new_predict = model.predict(new_input)
y_new_predict

array([0, 1])

In [86]:
n = 1

for i in y_new_predict:
  print('No', n, '=>:', y_le.classes_[i])
  n+=1

No 1 =>: no
No 2 =>: yes
